### ISSUE TITLE
slide-area width computation off on Firefox. sometimes doesn't fix on resize

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#175]
Reported in Zendesk no. 782.

Firefox miscalculates the available width for the slide content, e.g.: 
![Firefox demonstrating clipped slide](https://cloud.githubusercontent.com/assets/46313/5185777/6f6578da-7487-11e4-9e29-e318dafe7d34.png)

The same size window on Chrome fits the text nicely:
![Chrome example](https://cloud.githubusercontent.com/assets/46313/5185801/94fa3f36-7487-11e4-9c83-e0cc5f37b760.png)

This problem with miscalculated available space occasionally shows on Firefox on other storymaps on page load, including the example on storymap.knightlab.com. However, it usually gets corrected on resize, and seems to relate to having assets cached, as I can't consistently see the issue after first load on the front page example or on http://storymap.knightlab.com/examples/sochi-2014-olympic-torch-relay.html

**Comment by geoandrew** [comment]
This is also a repeatable problem with IE 10 and 11.

![image](https://cloud.githubusercontent.com/assets/11432770/6609964/35e352a2-c816-11e4-930b-eafab3c1a7fd.png)

**Comment by lukerague** [comment]
This is coming from `display: table;` and `max-width: 100%;` on `.vco-slide-content`. Display: table and max-width do not mesh in Firefox (and IE as well). It's listed as an unconfirmed bug for Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=975632), likely because of its intermittence. But there are enough other people experiencing the same problem that I'm sure it's causing our issue.

I do't want to get into the middle of a pro-table/anti-table argument, but simply turning off 'display: table' for `.vco-slide-content` fixes the bugs in Firefox, IE10, and IE11, without any adverse layout side-effects that I have observed.

Bar a better suggestion from @hbillings or @zachwise, I'll submit a pull request with this implemented.

**Comment by zachwise** [comment]
that will break vertical centering



—
Zach Wise

646.389.9473

zachwise.com




(sent from my iPhone)

**Comment by lukerague** [comment]
Not that I've found. Except in the case of slides that are overflowing, I'm not seeing any changes, in any screen size, to the slides when it's excluded.

Below the ~650 break-point, it sheds this style anyways.

**Comment by zachwise** [comment]
it will when text is longer than photo is high I believe



—
Zach Wise

646.389.9473

zachwise.com




(sent from my iPhone)

**Comment by lukerague** [comment]
Okay, fair enough. That must be the wiggle I'm seeing when it's turned on and off. I haven't seen this manifest in any dramatic changes, but on Monday I'll look harder for/manufacture such a case to see how bad this can be.

**Comment by lukerague** [comment]
So with five big paragraphs of lorem ipsum text, this is the difference between `display: table;` being on an off (taken from Firefox, but uniform across all browsers):
On: 
![screenshot 108](https://cloud.githubusercontent.com/assets/7632315/6672142/58569900-cbd8-11e4-9a36-b8a57fe2f98a.png)

Off: 
![screenshot 109](https://cloud.githubusercontent.com/assets/7632315/6672148/66445b24-cbd8-11e4-8f32-0fc373136115.png)

The couple pixels of breathing room it gives on the top actually improves the layout, imo.

I was mistaken when I said that it sheds the style under the break point, but when you turn it off in this format, there isn't even the wiggle of movement. 

I see no reason this fix won't work.

**Comment by zachwise** [comment]
Sounds good.

**Comment by geoandrew** [comment]
Thanks for looking into this so quickly. That did the trick!
