### ISSUE TITLE
Require Mapbox access token when using Mapbox base layer

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#213]
As part of changes to Mapbox's service, loading the javascript now requires an access token. We now understand that this access token is used for billing, so we should require that users enter their own access token, which should be used [when loading Mapbox tiles](https://github.com/NUKnightLab/StoryMapJS/blob/master/source/js/map/leaflet/VCO.Map.Leaflet.js#L177).

Near the field where we request this from users, we can link to [this Mapbox page](https://www.mapbox.com/help/define-access-token/) which gives more information.

Since there are maps in the wild depending upon our access token, we should continue to use it as a default, but the authoring tool should insist that new maps created to use Mapbox layers be accompanied by a new access token.

To the extent possible, we should also force users editing existing maps using Mapbox to enter their own access token, but if that seems like a snarl, we could break that into a separate issue and prioritize it separately.

**Comment by jywsn** [comment]
Do you have a non-default mapbox access token so I can test?

**Comment by JoeGermuska** [comment]
sent via Slack PM

**Comment by jywsn** [comment]
Should be fixed by ee1b625f4c1ccb48e7204d2c5b40387873fe1f6a + 6fa54b35932719f697c99bbc63b6386b5ce24d74

Deployed to stg

If someone is using mapbox and doesn't have a map_access_key set in their json, the editor should popup the storymap options modal (with the "error" highlighted).  And then they can't close that modal until they enter an access token (or change the type of map they are using).

**Comment by jywsn** [comment]
release 0.4.8

**Comment by abooabcker** [comment]
How deploy a django project with mapbox
