### ISSUE TITLE
Using the developer environment outside Knightlab

### ISSUE THREAD

**Issue by cr3ative** [NUKnightLab/StoryMapJS#255]
Hello!

I've been trying to set up the Dev environment, but I'm not within Knightlab, so I don't have access (quite rightly!) to the "secrets" repository. This appears to break quite a lot of important things.

I have a few questions if you'll entertain them:

- What's the dev environment meant to do? 
- The JS and CSS, etc, all loads from Knightlab's S3 bucket even when served from fab - rather than localhost - is this expected?

If it's useful, I put a few hacky shims in place to get `fab serve` basically working without the secrets repo: https://github.com/cr3ative/StoryMapJS/commit/17b9d2f8467faee2f9c6f635fb9848d766197c11

(This was useful to me as I could rebuild the JS/CSS on demand and have it serve from the same location, without making symlinks all over the place etc.)

Yours in slight confusion,
Paul

**Comment by JoeGermuska** [comment]
When StoryMapJS was originally created, the authoring tool was a pure HTML/CSS/JS application which used the Google Drive API for long-term storage of StoryMap JSON configuration and uploaded files. `fab serve` ran a simple local HTTP server and provided access to the authoring tool and a way to preview changes to the JS/CSS.

We found the Google Drive API unreliable and prone to changing without advance knowledge, such that we'd have to scramble to restore functionality to people who had published stories or were trying to write them.

This led us to rearchitect the system to use Amazon S3 for storage. There's no sensible way for us to securely use S3 without a server-side component which can hide the S3 access credentials from the public. So the new Flask server provides that intermediary (and also uses a MongoDB to store some metadata about a user's StoryMaps to avoid the overhead of listing S3 buckets).

This switchover was done in some haste, which is probably why the references to the javascript are to the `/dev/` path on our CDN instead of a local directory. That's definitely a thing which should be fixed.

While we love, in principle, offering our tools so that the public can contribute, in practice there hasn't been much interest, so we've chosen to skip the overhead of maintaining a development environment that works for people who don't have access to our secure credentials.

Since `fab build` works without `secrets` I don't think we'll bother any time soon with fixing `fab serve`. I'd recommend you use a simple local http server like Node's `http-server` or Python's `python -m SimpleHTTPServer` (Python 2) or `python -m http.server` (Python 3)

Make sense?

**Comment by cr3ative** [comment]
That's perfect, Joe. Thank you for taking the time to fill me in and provide workarounds. Very much appreciated!

**Comment by JoeGermuska** [comment]
Sure! And to clarify, the best way (probably) to test JS changes is using the local copy of the embed page... so if you have the local server running in the repository root on 8000, this is a URL that would always fire up a storymap:

`http://localhost:8000/build/embed/index.html?url=/compiled/examples/population.json`

Of course you can put your own example JSON anywhere under the root, but the `/compiled/` dir is where @zachwise does his fundamental development, being more a fan of CodeKit than of command line servers. Thus there are lots of good test JSON files in there.
