### ISSUE TITLE
Environment variables for running local server

### ISSUE THREAD

**Issue by binary-koan** [NUKnightLab/StoryMapJS#290]
Hi,

When I try to run `fab serve` (after following the instructions in the readme) it throws an error because a required environment variable isn't set (FLASK_SECRET_KEY)

Looking in core/settings.py, it seems like all the environment variables listed there would need to be defined for the server to work. Should I just put any old values in for them (since I don't have an AWS account or anything)? Does it matter if they're defined but blank?

TimelineJS3 didn't require me to set up any environment variables, so I'm curious why they're necessary here.

Cheers

**Comment by JoeGermuska** [comment]
Ah... StoryMapJS is rather more complicated because of the authoring tool. You shouldn't need to actually run `fab serve` unless you are working on those features. I've updated [README.md](https://github.com/NUKnightLab/StoryMapJS/blob/master/README.md) to try to better explain this.  It includes a few notes about how you should be able to workon the actual javascript without needing to run `fab serve`.

Hope that helps. Thanks for your interest.

**Comment by binary-koan** [comment]
Ah OK, I never thought of just running a static server ... I've successfully run examples and unit tests now, thanks :)
