### ISSUE TITLE
How to specific slide? - more info needed.

### ISSUE THREAD

**Issue by agrahamt** [NUKnightLab/StoryMapJS#331]
Hi,
I'm not sure how to link to a specific slide in my Storymap.  I saw your post about it, but am not sure how to apply it to my project.
Here's what is on the FAQ, I didn't know how to apply it (I've never embedded my project on a webpage, fyi, just working on it using the authoring tool):
How can I link to a specific slide?
You can add a parameter to the URL that is the value of the iframe src attribute, 'start_at_slide'.
Its value should be a number from 0 to one less than the total number of slides in the storymap.
For example: http://cdn.knightlab.com/libs/storymapjs/latest/embed/?url=//media.knightlab.com/StoryMapJS/demo/sochi.json&start_at_slide=5

This should load "Sochi 2014 Olympic Torch Relay Highlights: Slide 5."
What I tried was:
https://uploads.knightlab.com/storymapjs/29f2dd51f81c24f8305249344c8f0c2b/vectis-scenery/draft..json&start_at_slide=5
This didn't work, I got a "403-Forbidden."
Here's the share link to my project:
https://uploads.knightlab.com/storymapjs/29f2dd51f81c24f8305249344c8f0c2b/vectis-scenery/index.html

Apologies if I should know this - thanks, Andrew Taylor

**Comment by scott2b** [comment]
Hi Andrew,

Your link is malformed. There is an extra dot, and query parameters should be separated from the endpoint by `?` rather than by `&`. The link I think you want is 

`https://uploads.knightlab.com/storymapjs/29f2dd51f81c24f8305249344c8f0c2b/vectis-scenery/draft.json?start_at_slide=5` for the draft version and `https://uploads.knightlab.com/storymapjs/29f2dd51f81c24f8305249344c8f0c2b/vectis-scenery/published.json?start_at_slide=5` for the published version

**Comment by agrahamt** [comment]
Thanks Scott! - Andrew
