### ISSUE TITLE
Images renamed without file extension do not load

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#344]
When uploading media in the StoryMap editor, if the filename already exists a dialog will popup requesting the user to select to replace the original or to rename the upload. The rename option allows the user to enter a name that does not include the file extension, however when doing so, the resulting image is not loaded into the StoryMap

**Comment by rosaliechan** [comment]
Made a fix for this issue by automatically adding ".jpg" in the text box so that the user will know to add a file extension. If for some reason the user erases this, StoryMap will check for the file extensions jpg, png or gif. It also will trigger a warning saying 'You must enter a file extension like jpg, gif or png.' @scott2b See fixes here: https://github.com/NUKnightLab/StoryMapJS/blob/fileextension/static/js/modals.js

**Comment by scott2b** [comment]
Instead of giving a hint to the user and putting the burden of extension naming on the user, would it be possible to just append the extension from the original filename onto the new filename? So the general flow would be:

1. uploaded file fails due to name match. Rename is requested
2. user enters new name in standard box as before. With or without extension
3. system checks to see if there is an extension matching the extension of the original file. If not, that extension is appended to the new filename
4. image upload is completed

In addition to the automatic appending described above, you could give a hint to the user to include the extension as in your current approach, however if so, make the extension match the original file and place the cursor at the beginning of the input box, not at the end after the extension

**Comment by rosaliechan** [comment]
@scott2b now it automatically adds the extension: https://github.com/NUKnightLab/StoryMapJS/blob/fileextension/static/js/modals.js
