### ISSUE TITLE
Internal on https://storymap.knightlab.com/ broken on Chrome

### ISSUE THREAD

**Issue by joeytakeda** [NUKnightLab/StoryMapJS#438]
The two examples hosted by the Knight Lab--Arya's Journey (https://storymap.knightlab.com/examples/aryas-journey/) and The Garden of Early Delights (https://storymap.knightlab.com/examples/bosch-garden/)—aren't working in Chrome.

I suspect it's due to some CORS policy configuration from AWS. Console log error reads:

```
Access to XMLHttpRequest at 'https://s3.amazonaws.com/uploads.knightlab.com/storymapjs/a1a349b51799ee49e96bed10cc235e7f/garden-of-earthly-delights/published.json' from origin 'https://cdn.knightlab.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by JoeGermuska** [comment]
I'm unable to reproduce this. Both of those work on Chrome 80.0.3987.162 on my Macbook.

Sometimes CORS errors are thrown when the response yields an error page instead of the intended result, as error pages often don't go through the same policy. But without being able to reproduce it and inspect the actual response returned, I don't know what we can do about it.  Are you still experiencing the error?

**Comment by joeytakeda** [comment]
It was a Chrome issue, actually; I was using 80.0.3987.148. Thanks for checking, though!
