### ISSUE TITLE
Emergency help with pulling image in StorymapJS

### ISSUE THREAD

**Issue by Spica2021** [NUKnightLab/StoryMapJS#490]
Emergency! Help! I followed the tutorial https://www.gilderlehrman.org/sites/default/files/inline-pdfs/storymapjs_gigapixel_tutorial.pdf
and https://github.com/NUKnightLab/StoryMapJS/blob/master/GITHUB_HOSTING/GITHUB_HOSTING.md 
to host my zoomified tiles of an image and get an url that ends with .git that won't pull the image in StoryMapJS as a base image to replace the default map. What kind of url should I get to set this straight? Or what might have I done wrong? It's urgent, please respond asap. Thank you!

**Comment by JoeGermuska** [comment]
This would be better suited as [a request through our online help system](https://knightlab.zendesk.com/hc/en-us/requests/new), but since it's here, we'll answer it here.

I looked at your Git homepage and found the repository URL that seems to have Gigapixel tiles in it -- but it looks like you haven't made the repository a GitHub pages repository. It would appear that the [GITHUB_HOSTING.md](https://github.com/NUKnightLab/StoryMapJS/blob/master/GITHUB_HOSTING/GITHUB_HOSTING.md) is out of sync with the current GitHub interface.  

Unfortunately, we aren't able to update this document with emergency urgency. It seems that what you need to do the current equivalent of step #7 from `GITHUB_HOSTING.md`  I see that there's a "pages" option on the left-hand rail after one click's "settings" on a repository. That's the general area in which to work. Once you've done that correctly, I think the URL you want will be https://Spica2021.github.io/Ed-Wilson-Oral-History/

Let me also note, though, that it seems from your [ImageProperties.xm](https://github.com/Spica2021/Ed-Wilson-Oral-History/blob/main/ImageProperties.xml) file that you've started with a not particularly large image. We recommend that your gigapixel source image be at least 10,000 pixels on at least one dimension. But you can judge for yourself, once you complete the GitHub Pages publishing process.
