### ISSUE TITLE
Custom CSS Styles get overwritten by defaults when using the import feature.

### ISSUE THREAD

**Issue by arch8-xyz** [NUKnightLab/StoryMapJS#493]
Hello,

Pretty much as the title suggests, on using export-->edit locally(JSON and CSS Styles)---->Import workflow, all the custom css gets overwritten to be defaults. I am using "map as an image" option to build a storymap here. Please help.

**Comment by JoeGermuska** [comment]
For what it's worth, the import/export function was designed for moving a StoryMap from one account to another rather than to support local edits that could then be uploaded.

If you're implementing the custom CSS in the HTML files, that would definitely get lost, as the StoryMap editor doesn't have a concept of merging local changes to HTML with the master template that is used to create those for all storymaps. 

If you want custom CSS, our recommendation would be to instantiate the storymap on a page under your own control. We are not likely to implement changes to the editor which support uploading custom CSS through this path.
